spring:
  datasource:
    url: jdbc:h2:mem:oauth1
    username: oauth
    password: oauth

  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8082

aw:
  auth:
    provider-uri: "http://localhost:8082"
    jks:
      keypass: 123456
      storepass: 123456
      alias: awblog
      path: keystore/awblog.jks
